Invalid HTTP_HOST header: 'dressdrive.sebasmd.com'. You may need to add 'dressdrive.sebasmd.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/sebasmdc/virtualenv/python_apps/dressdrive/3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sebasmdc/virtualenv/python_apps/dressdrive/3.10/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/sebasmdc/virtualenv/python_apps/dressdrive/3.10/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/sebasmdc/virtualenv/python_apps/dressdrive/3.10/lib/python3.10/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'dressdrive.sebasmd.com'. You may need to add 'dressdrive.sebasmd.com' to ALLOWED_HOSTS.
Bad Request: /
